### ISSUE TITLE
new release tag, for OCEAN, by 2023-05-19

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#607]
blocked by 

- [x] https://github.com/insightsengineering/rtables/issues/606
- [x] https://github.com/insightsengineering/rtables/pull/631

# TODOs

- [x]  Upstream formatters version bump to 0.5.0
- [x] #636
- [x]  Tag the update as a release candidate, v0.6.1-rc1
- [x]  Submit v0.6.1-rc1 for validation
- [x]  Get v0.6.1-rc1 validated, retag as v0.6.1
- [x]  Update downstream package dependencies to (>=0.6.1) in chevron
- [x]  Update downstream package dependencies to (>=0.6.1) in citril
