### ISSUE TITLE
prepare for ocean 0.6.2 release

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#678]
- [x] - https://github.com/insightsengineering/rtables/issues/670 
- [x] - nice to have, not mandatory https://github.com/insightsengineering/rtables/issues/653
- [ ] ~- nice to have https://github.com/insightsengineering/rtables/issues/651~
- [ ] ~#665~ 
- [x] https://github.com/insightsengineering/rtables/issues/672
- [ ]  ~https://github.com/insightsengineering/rtables/issues/630 @khatril can you please follow-up with @Teninq~
- [x]  create ocean_releae_0.6.2_branch
- [x] vbump formatters v0.5.1
- [x]  check NEWS.md, README, update DESCRIPTION
- [x]  Submission to OCEAN
- [x]  Address any OCEANfeedback
- [x]  Acceptance on OCEAN
- [x]  merge ocean_releae_0.6.2_branch
- [x]  tag v0.6.2

**Comment by Melkiades** [comment]
can we include also #665?

**Comment by shajoezhu** [comment]
> can we include also https://github.com/insightsengineering/rtables/pull/665?

yes
